//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class GuestHouseManagementSystemEntities2 : DbContext
{
    public GuestHouseManagementSystemEntities2()
        : base("name=GuestHouseManagementSystemEntities2")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<BookingApproval> BookingApprovals { get; set; }
    public DbSet<BookingRequest> BookingRequests { get; set; }
    public DbSet<Guest> Guests { get; set; }
    public DbSet<GuestHouseAdministrator> GuestHouseAdministrators { get; set; }
    public DbSet<Rent> Rents { get; set; }
    public DbSet<ReservationApproval> ReservationApprovals { get; set; }
    public DbSet<ReservationRequest> ReservationRequests { get; set; }
    public DbSet<RoomForRent> RoomForRents { get; set; }
    public DbSet<RoomMaintenaceAndServiceInfo> RoomMaintenaceAndServiceInfoes { get; set; }
    public DbSet<ThirdPartyRequester> ThirdPartyRequesters { get; set; }
}
