//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class BookingApproval
{
    public int BookingOrderNumber { get; set; }
    public Nullable<System.DateTime> DateBookingProcessed { get; set; }
    public Nullable<int> RoomNumber { get; set; }
    public string StaffAdminEmail { get; set; }
    public string GuestIDNumber { get; set; }

    public virtual Guest Guest { get; set; }
    public virtual GuestHouseAdministrator GuestHouseAdministrator { get; set; }
    public virtual RoomForRent RoomForRent { get; set; }
    public virtual BookingRequest BookingRequest { get; set; }
    public virtual Rent Rent { get; set; }
    public virtual ReservationApproval ReservationApproval { get; set; }
}

public partial class BookingRequest
{
    public int BookingRequestNumber { get; set; }
    public System.DateTime BookingRequestedDate { get; set; }
    public int BookingOrderNumber { get; set; }
    public string GuestIDNumber { get; set; }
    public int ThirdPartyRequesterID { get; set; }

    public virtual BookingApproval BookingApproval { get; set; }
    public virtual Guest Guest { get; set; }
    public virtual ThirdPartyRequester ThirdPartyRequester { get; set; }
}

public partial class Guest
{
    public Guest()
    {
        this.BookingApprovals = new HashSet<BookingApproval>();
        this.BookingRequests = new HashSet<BookingRequest>();
        this.ReservationRequests = new HashSet<ReservationRequest>();
    }

    public string GuestLastName { get; set; }
    public string GuestFirstName { get; set; }
    public string GuestIDNumber { get; set; }
    public Nullable<System.DateTime> DateGuestRegistered { get; set; }
    public Nullable<System.DateTime> DipartureDateOrCheckOut { get; set; }
    public string GuestEmailAddress { get; set; }
    public string GuestNationality { get; set; }
    public string GuestNationalPassportUNLP { get; set; }
    public System.DateTime ArrivalDateOrCheckInDate { get; set; }
    public string GuestOfficialTitlte { get; set; }
    public string GuestResidenceStatus { get; set; }
    public string GuestTelephoneContact { get; set; }

    public virtual ICollection<BookingApproval> BookingApprovals { get; set; }
    public virtual ICollection<BookingRequest> BookingRequests { get; set; }
    public virtual ICollection<ReservationRequest> ReservationRequests { get; set; }
}

public partial class GuestHouseAdministrator
{
    public GuestHouseAdministrator()
    {
        this.BookingApprovals = new HashSet<BookingApproval>();
        this.ReservationApprovals = new HashSet<ReservationApproval>();
    }

    public string StaffAdminEmail { get; set; }
    public string StaffAdminPassword { get; set; }
    public string StaffAdminFirstName { get; set; }
    public string StaffAdminLastName { get; set; }

    public virtual ICollection<BookingApproval> BookingApprovals { get; set; }
    public virtual ICollection<ReservationApproval> ReservationApprovals { get; set; }
}

public partial class Rent
{
    public int RentProcessNumber { get; set; }
    public int BookingOrderNumber { get; set; }
    public Nullable<decimal> RentDueForBooking { get; set; }

    public virtual BookingApproval BookingApproval { get; set; }
}

public partial class ReservationApproval
{
    public Nullable<System.DateTime> DateReservationMade { get; set; }
    public Nullable<int> RoomNumber { get; set; }
    public string StaffAdminEmail { get; set; }
    public int BookingOrderNumber { get; set; }
    public string GuestIDNumber { get; set; }

    public virtual BookingApproval BookingApproval { get; set; }
    public virtual GuestHouseAdministrator GuestHouseAdministrator { get; set; }
    public virtual RoomForRent RoomForRent { get; set; }
    public virtual ReservationRequest ReservationRequest { get; set; }
}

public partial class ReservationRequest
{
    public System.DateTime ReservationRequestedDate { get; set; }
    public int ThirdPartyRequesterID { get; set; }
    public string GuestIDNumber { get; set; }
    public int BookingOrderNumber { get; set; }

    public virtual Guest Guest { get; set; }
    public virtual ReservationApproval ReservationApproval { get; set; }
    public virtual ThirdPartyRequester ThirdPartyRequester { get; set; }
}

public partial class RoomForRent
{
    public RoomForRent()
    {
        this.BookingApprovals = new HashSet<BookingApproval>();
        this.ReservationApprovals = new HashSet<ReservationApproval>();
        this.RoomMaintenaceAndServiceInfoes = new HashSet<RoomMaintenaceAndServiceInfo>();
    }

    public int RoomNumber { get; set; }
    public string RoomInformation { get; set; }
    public string RoomOccupancyStatus { get; set; }

    public virtual ICollection<BookingApproval> BookingApprovals { get; set; }
    public virtual ICollection<ReservationApproval> ReservationApprovals { get; set; }
    public virtual ICollection<RoomMaintenaceAndServiceInfo> RoomMaintenaceAndServiceInfoes { get; set; }
}

public partial class RoomMaintenaceAndServiceInfo
{
    public int RoomMaintenaceInfoLogNumber { get; set; }
    public Nullable<int> RoomNumber { get; set; }
    public string RoomMaintenanceRemark { get; set; }
    public Nullable<System.DateTime> RoomMaintenanceDate { get; set; }

    public virtual RoomForRent RoomForRent { get; set; }
}

public partial class ThirdPartyRequester
{
    public ThirdPartyRequester()
    {
        this.BookingRequests = new HashSet<BookingRequest>();
        this.ReservationRequests = new HashSet<ReservationRequest>();
    }

    public string ThirdPartyRequestByFName { get; set; }
    public string ThirdPartyRequestByLName { get; set; }
    public string ThirdPartyRequestByEmail { get; set; }
    public string ThirdPartyRequestByMobile { get; set; }
    public Nullable<int> BookingRequestNumber { get; set; }
    public int ThirdPartyRequesterID { get; set; }

    public virtual ICollection<BookingRequest> BookingRequests { get; set; }
    public virtual ICollection<ReservationRequest> ReservationRequests { get; set; }
}
